target  = 420ToNv12
sources = main.c $(target).c
objects = $(patsubst %.c,%.o,$(sources))
CC = gcc
OPTS = -Wall -fopenmp

all: $(objects)
	$(CC) $(OPTS) -o $(target) $(objects)

420ToNv12.o: 420ToNv12.c
	$(CC) $(OPTS) -c $<

clean:
	$(RM) $(target) $(objects)
